---
apiVersion: v1
kind: Namespace
metadata: 
    name: blog-app-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: blog-app-namespace
  name:  blog-app-deployment
spec:
  selector:
    matchLabels:
        app.kubernetes.io/name: blog-app
  replicas: 2
  template:
    metadata:
       labels:
          app.kubernetes.io/name: blog-app
    spec:
      containers:
         - image: anjalishreya1/blogapplicationdjnago:latest
           imagePullPolicy: Always
           name: blog-app
           ports: 
            - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
   namespace: blog-app-namespace
   name: blog-app-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector: 
      app.kubernetes.io/name: blog-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   namespace: blog-app-namespace
   name: blog-app-ingress
   annotations:
       alb.ingress.kubernetes.io/scheme: internet-facing
       alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb  
  rules:
   - host:  www.blogapp.in
     http:
       paths:
        - path: /
          pathType: Prefix
          backend:
             service:
                name: blog-app-service
                port: 
                 number: 80
            

    
